import {useHistory} from 'react-router-dom'
import {useDispatch} from 'react-redux'
import {useSelector} from 'react-redux'



export default function ZendoBegin ({attended}) {

    //second component called in the zendo sequence
    //shows user how many people are sitting with them via CSS animations
    //images generated by imageMaker and makeArray

    //for the button
    const history = useHistory()
    const dispatch = useDispatch()
    const sessionInfo = useSelector(store=>store.zendo)

    const handleClick = () =>{
        console.log('leave room')
        //update DB that user has left?
        dispatch({type: 'UPDATE_EVENT', payload: {id: sessionInfo.id, left: true}})
        history.push('/user')
    }

    //makeArray lets me generate imgs on the screen, one for each person sitting
    function makeArray(number) {
        let array = []
        let counter = 0;
        for(let i = 0; i < number; i++){
            array.push(`cloud_${counter++}`)
        }
        console.log(array)
        return array
    }
    //logs that tone has played, makes tone only play once
    const handlePlay = (event) =>{
        let sound = event.target;
        sound = null;
        console.log('sound played')
    }

    //imageMaker becomes the array I loop over to generate visual representation of people sitting
    const imageMaker = makeArray(attended);

    return(
        <>
        <audio id="musicplayer" type="audio/mp3" autoPlay onPlay={(event)=>handlePlay(event)}>
            <source src="/zendo/start_3_bells.mp3"/>
        </audio>
        <div className="header">
        <h3>People sitting with you: {attended}</h3>
        <button className="delete" onClick={()=>{handleClick()}}>Back to User Portal</button>
        </div>
        {imageMaker.map((object)=>{
            return(
                <img key={object} className={object} src="/zendo/cloud_1.png" alt="cloud" />
            )
        })}
        </>

    )
}
